config/routes.rb
Rails.application.routes.draw do

  get 'pots/filter/:tag', to: 'posts#index', as: 'tag'

  resources :approvals, only: [:index]

  put '/approvals/pcomment/:id', to: 'pcomments#approve'
  put '/approvals/ccomment/:id', to: 'ccomments#approve'
  delete '/approvals/pcomment/:id', to: 'pcomments#disapprove'
  delete '/approvals/ccomment/:id', to: 'ccomments#disapprove'

  put '/like/ccomment/:id', to: 'ccomments#like'
  put '/dislike/ccomment/:id', to: 'ccomments#dislike'
  put '/like/pcomment/:id', to: 'pcomments#like'
  put '/dislike/pcomment/:id', to: 'pcomments#dislike'

  resources :posts do
    resources :pcomments do
      resources :ccomments
    end
  end

  root 'posts#index'

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/ccomment.rb
class Ccomment < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  belongs_to :pcomment
  belongs_to :post

  validates_presence_of :pcomment, :name, :message

end

app/controllers/ccomments_controller.rb
class CcommentsController < ApplicationController

  before_action :set_post, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy, :approve, :disapprove, :like, :dislike]

  def create
    if @post.comments_disabled?
      redirect_to post_path(@post), alert: 'Comments not allowed here'
    else
      @pcomment          = @post.pcomments.find(params[:pcomment_id])
      @ccomment          = @pcomment.ccomments.build(post_params)
      @ccomment.post_id  = @post.id
      @ccomment.approved = !@post.comments_approval?

      unless current_user.nil?
        @ccomment.user_id  = current_user.id
        @ccomment.approved = @ccomment.approved ? true : (current_user == @post.user)
      end

      approval = !@ccomment.approved ? ' waiting for approval' : ' saved'
      msg      = @ccomment.save ? 'Comment' + approval : 'Unable to save comment: ' + @ccomment.errors.full_messages.join('. ')
      redirect_to post_path(@post), notice: msg
    end
  end

  def approve
    #user approves comment
    @ccomment.approved = true
    @ccomment.save
    redirect_to :back, :notice => 'Comment was approved'
  end

  def disapprove
    @ccomment.destroy
    redirect_to :back, :notice => 'Comment was deleted'
  end

  def like
    unless current_user.nil?
      current_user.likes @ccomment
      redirect_to :back, :notice => 'Comment was liked'
    end
  end

  def dislike
    unless current_user.nil?
      current_user.dislikes @ccomment
      redirect_to :back, :notice => 'Comment was disliked'
    end
  end

  def destroy
    @pcomment = @post.pcomments.find(params[:pcomment_id])
    @ccomment = @pcomment.ccomments.find(params[:id])
    @ccomment.destroy
    redirect_to post_path(@post), :notice => 'Comment was deleted'
  end

  private
  def set_comment
    @ccomment = Ccomment.find(params[:id])
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  private

  def post_params
    params.require(:ccomment).permit(:post_id, :pcomment_id, :name, :message)
  end
end

app/helpers/ccomments_helper.rb
module CcommentsHelper
  def get_like_class(ccomment)
    if !current_user.nil? and current_user.voted_up_on? ccomment
      'color:blue'
    else
      'color:gray'
    end
  end

  def get_dislike_class(ccomment)
    if !current_user.nil? and current_user.voted_down_on? ccomment
      'color:red'
    else
      'color:gray'
    end
  end
end

app/views/ccomments/_ccomment.slim
/- model_class = Ccomment
/- if can? :read, ccomment
  - unless ccomment.id.nil?
    div class='ccomment'
      p
        - if ccomment.user.nil?
          ' Anonymous user:
          =' ccomment.name
        - else
          ' Registered user:
          =' ccomment.user.user_name
        ' likes:
        =' ccomment.get_likes.size
        - if can? :like, ccomment
          = link_to t("helpers.links.like"), "/like/ccomment/#{ccomment.id}", :method => :put, :class => get_like_class(ccomment)
        ' dislikes:
        =' ccomment.get_dislikes.size
        - if can? :dislike, ccomment
          = link_to t("helpers.links.dislike"), "/dislike/ccomment/#{ccomment.id}", :method => :put, :class => get_dislike_class(ccomment)
        br
        = ccomment.message
        br
        - if can? :update, ccomment and !ccomment.approved
          = link_to t("helpers.links.approve"), "/approvals/ccomment/#{ccomment.id}", :method => :put, :class => 'btn btn-default btn-xs'
          '
          = link_to t("helpers.links.disapprove"), "/approvals/ccomment/#{ccomment.id}", :method => :delete, :class => 'btn btn-danger btn-xs'
        - if can? :destroy, ccomment and !post.nil?
          = link_to t("helpers.links.destroy"), post_pcomment_ccomment_path(post, pcomment, ccomment), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger btn-xs'
      br
- model_class = Ccomment
- if can? :read, ccomment
  - unless ccomment.id.nil?
    div.comment-container
      div.comments-display
        ul.posted-comments
          li
            div.avatar.pull-left
              - if ccomment.user.nil?
                img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" border="0"
              - else
                = image_tag(ccomment.user.avatar.url(:thumb), :class => 'image-30')
            div.posted-comment-container
              div.posted-comment-head
                span.posted-comment-title
                  - if can? :update, ccomment and !ccomment.approved
                    br
                    = link_to raw(fa_icon("times", class: "fa-2x")),
                      "/approvals/ccomment/#{ccomment.id}",
                      :method => :delete,
                      :style => "color:#c9302c",
                      :class => "pull-right"
                    '
                    = link_to raw(fa_icon("check", class: "fa-2x")),
                      "/approvals/ccomment/#{ccomment.id}",
                      :method => :put,
                      :style => "color:#428bca",
                      :class => "pull-right"
                  - if ccomment.user.nil?
                    = ccomment.name
                  - else
                    = ccomment.user.user_name
                span.dot •
                span.real-time =ccomment.updated_at.to_datetime.strftime("%d %h %Y %H:%M:%S")
              div.posted-comment-body
                div.posted-comment-txt
                  = ccomment.message
              div.posted-comment-foot
                - if can? :destroy, ccomment and !post.nil?
                  span.post-edit
                    = link_to raw(fa_icon("trash", class: "fa-2x")),
                      post_pcomment_ccomment_path(post, pcomment, ccomment),
                      :method => "delete",
                      :data => { :confirm => 'Are you sure' },
                      :class => "pull-right"
                  span.dot •
                  - if can? :like, pcomment
                    = link_to raw(fa_icon("thumbs-up", class: "fa-2x")),
                      "/like/ccomment/#{ccomment.id}",
                      :method => :put,
                      :style => get_like_class(ccomment)
                  | (#{ccomment.get_likes.size})
                  span.dot •
                  -if can? :dislike, ccomment
                    = link_to raw(fa_icon("thumbs-down", class: "fa-2x")),
                      "/dislike/ccomment/#{ccomment.id}",
                      :method => :put,
                      :style => get_dislike_class(ccomment)
                  | (#{ccomment.get_dislikes.size})
            div.clear

app/views/ccomments/_form.slim
/= form_for ([post, pcomment, pcomment.ccomments.build]), html: { class: "form form-horizontal ccomment" } do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control', :readonly => !current_user.nil?, :value => current_user ? current_user.email : ''
    /= error_span(@ccomment[:name])
  .form-group
    = f.label :message, :class => 'control-label'
    .controls
      = f.text_field :message, :class => 'form-control'
    /= error_span(@ccomment[:message])
  = f.submit 'Save comment comment', :class => 'btn btn-primary'a

.posted-comments-postbox
  .avatar
    - if current_user.nil?
      img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" border="0"
    - else
      = image_tag(current_user.avatar.url(:thumb), :class => 'image-30')
  = form_for ([post, pcomment, pcomment.ccomments.build]), html: { class: "form ccomment" } do |f|
    .form-group
      .input-group.input-group-sm
        span.input-group-addon @
        = f.text_field :name, :type => 'text', :class => 'form-control', :placeholder => 'Username', :readonly => !current_user.nil?, :value => current_user ? current_user.email : ''
    .form-group
      .controls
        = f.text_area :message, :placeholder => 'Message', :class => 'form-control'
    = f.submit 'Comment', :class => 'btn btn-primary pull-right'